# Generated by Django 3.2.7 on 2021-09-06 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
